// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEE43GdQ3BcIUL_0UtSD9koOD2vaNvNE',
    appId: '1:731853873025:android:fc9e272c27f5c2eb551280',
    messagingSenderId: '731853873025',
    projectId: 'fruit-market-9fcbd',
    storageBucket: 'fruit-market-9fcbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-djU-gx-0v2yjV4D8gVw2Ohs2gjT3bE',
    appId: '1:731853873025:ios:aa70eb0c077a0d6d551280',
    messagingSenderId: '731853873025',
    projectId: 'fruit-market-9fcbd',
    storageBucket: 'fruit-market-9fcbd.firebasestorage.app',
    androidClientId:
        '731853873025-ghj7ohgg6gfe8galahhqsovsm98hpf92.apps.googleusercontent.com',
    iosClientId:
        '731853873025-u09f58inm3me9ojs18efgcsorj17965u.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );
}
